name: Build & Push Docker image

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Gitea Container Registry
        uses: docker/login-action@v3
        with:
          registry: 192.168.10.103:3005
          username: ${{ gitea.actor }}
          password: ${{ secrets.GITEA_TOKEN }}

      - name: Extract metadata
        id: meta
        run: |
          REPO_PATH=$(echo "${GITHUB_REPOSITORY}" | tr '[:upper:]' '[:lower:]')
          VERSION=${GITHUB_REF_NAME#v}   # "v" を削除
          echo "repo_path=${REPO_PATH}" >> $GITHUB_OUTPUT
          echo "version=${VERSION}" >> $GITHUB_OUTPUT

      - name: Build and push image (amd64 only)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            192.168.10.103:3005/${{ steps.meta.outputs.repo_path }}:${{ steps.meta.outputs.version }}
            192.168.10.103:3005/${{ steps.meta.outputs.repo_path }}:latest
