name: Build & Push Docker image
on:
  push:
    tags:
      - "v*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Extract metadata
        id: meta
        run: |
          REPO_PATH=$(echo "${GITHUB_REPOSITORY}" | tr '[:upper:]' '[:lower:]')
          VERSION=${GITHUB_REF_NAME#v}   # "v" を削除
          echo "repo_path=${REPO_PATH}" >> $GITHUB_OUTPUT
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          echo "Repository: ${REPO_PATH}"
          echo "Version: ${VERSION}"
      
      - name: Build Docker image to local daemon
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: false  # ローカルDockerデーモンにのみ保存
          load: true   # ローカルDockerデーモンにロード
          tags: |
            ${{ steps.meta.outputs.repo_path }}:${{ steps.meta.outputs.version }}
            ${{ steps.meta.outputs.repo_path }}:latest
      
      - name: Verify built images
        run: |
          echo "Built Docker images:"
          docker images | grep "${{ steps.meta.outputs.repo_path }}"
          echo "Docker daemon info:"
          docker system info | grep "Docker Root Dir"